[package]
name = "sim-3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.1"
bevy_egui = "0.26"
bevy_xpbd_3d = "0.4"
rand = "0.8.5"
bevy_flycam = "0.13.0"
vleue_navigator = "0.7"